################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/GC9A01A_Driver/Src \
Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/lvgl-master/demos/benchmark/assets \
Drivers/lvgl-master/demos/benchmark \
Drivers/lvgl-master/demos/flex_layout \
Drivers/lvgl-master/demos/keypad_encoder \
Drivers/lvgl-master/demos/music/assets \
Drivers/lvgl-master/demos/music \
Drivers/lvgl-master/demos/stress \
Drivers/lvgl-master/demos/widgets/assets \
Drivers/lvgl-master/demos/widgets \
Drivers/lvgl-master/env_support/pikascript \
Drivers/lvgl-master/env_support/rt-thread \
Drivers/lvgl-master/env_support/rt-thread/squareline \
Drivers/lvgl-master/examples/anim \
Drivers/lvgl-master/examples/assets \
Drivers/lvgl-master/examples/assets/emoji \
Drivers/lvgl-master/examples/event \
Drivers/lvgl-master/examples/get_started \
Drivers/lvgl-master/examples/layouts/flex \
Drivers/lvgl-master/examples/layouts/grid \
Drivers/lvgl-master/examples/libs/barcode \
Drivers/lvgl-master/examples/libs/bmp \
Drivers/lvgl-master/examples/libs/ffmpeg \
Drivers/lvgl-master/examples/libs/freetype \
Drivers/lvgl-master/examples/libs/gif \
Drivers/lvgl-master/examples/libs/png \
Drivers/lvgl-master/examples/libs/qrcode \
Drivers/lvgl-master/examples/libs/rlottie \
Drivers/lvgl-master/examples/libs/sjpg \
Drivers/lvgl-master/examples/libs/tiny_ttf \
Drivers/lvgl-master/examples/others/file_explorer \
Drivers/lvgl-master/examples/others/fragment \
Drivers/lvgl-master/examples/others/gridnav \
Drivers/lvgl-master/examples/others/ime \
Drivers/lvgl-master/examples/others/imgfont \
Drivers/lvgl-master/examples/others/monkey \
Drivers/lvgl-master/examples/others/msg \
Drivers/lvgl-master/examples/others/snapshot \
Drivers/lvgl-master/examples/porting \
Drivers/lvgl-master/examples/scroll \
Drivers/lvgl-master/examples/styles \
Drivers/lvgl-master/examples/widgets/animimg \
Drivers/lvgl-master/examples/widgets/arc \
Drivers/lvgl-master/examples/widgets/bar \
Drivers/lvgl-master/examples/widgets/btn \
Drivers/lvgl-master/examples/widgets/btnmatrix \
Drivers/lvgl-master/examples/widgets/calendar \
Drivers/lvgl-master/examples/widgets/canvas \
Drivers/lvgl-master/examples/widgets/chart \
Drivers/lvgl-master/examples/widgets/checkbox \
Drivers/lvgl-master/examples/widgets/colorwheel \
Drivers/lvgl-master/examples/widgets/dropdown \
Drivers/lvgl-master/examples/widgets/img \
Drivers/lvgl-master/examples/widgets/imgbtn \
Drivers/lvgl-master/examples/widgets/keyboard \
Drivers/lvgl-master/examples/widgets/label \
Drivers/lvgl-master/examples/widgets/led \
Drivers/lvgl-master/examples/widgets/line \
Drivers/lvgl-master/examples/widgets/list \
Drivers/lvgl-master/examples/widgets/menu \
Drivers/lvgl-master/examples/widgets/meter \
Drivers/lvgl-master/examples/widgets/msgbox \
Drivers/lvgl-master/examples/widgets/obj \
Drivers/lvgl-master/examples/widgets/roller \
Drivers/lvgl-master/examples/widgets/slider \
Drivers/lvgl-master/examples/widgets/span \
Drivers/lvgl-master/examples/widgets/spinbox \
Drivers/lvgl-master/examples/widgets/spinner \
Drivers/lvgl-master/examples/widgets/switch \
Drivers/lvgl-master/examples/widgets/table \
Drivers/lvgl-master/examples/widgets/tabview \
Drivers/lvgl-master/examples/widgets/textarea \
Drivers/lvgl-master/examples/widgets/tileview \
Drivers/lvgl-master/examples/widgets/win \
Drivers/lvgl-master/src/core \
Drivers/lvgl-master/src/dev/disp/drm \
Drivers/lvgl-master/src/dev/disp/fb \
Drivers/lvgl-master/src/dev/sdl \
Drivers/lvgl-master/src/draw/arm2d \
Drivers/lvgl-master/src/draw/gd32_ipa \
Drivers/lvgl-master/src/draw \
Drivers/lvgl-master/src/draw/nxp/pxp \
Drivers/lvgl-master/src/draw/nxp/vglite \
Drivers/lvgl-master/src/draw/sdl \
Drivers/lvgl-master/src/draw/stm32_dma2d \
Drivers/lvgl-master/src/draw/sw \
Drivers/lvgl-master/src/draw/swm341_dma2d \
Drivers/lvgl-master/src/font \
Drivers/lvgl-master/src/hal \
Drivers/lvgl-master/src/layouts/flex \
Drivers/lvgl-master/src/layouts/grid \
Drivers/lvgl-master/src/libs/barcode \
Drivers/lvgl-master/src/libs/bmp \
Drivers/lvgl-master/src/libs/ffmpeg \
Drivers/lvgl-master/src/libs/freetype \
Drivers/lvgl-master/src/libs/fsdrv \
Drivers/lvgl-master/src/libs/gif \
Drivers/lvgl-master/src/libs/png \
Drivers/lvgl-master/src/libs/qrcode \
Drivers/lvgl-master/src/libs/rlottie \
Drivers/lvgl-master/src/libs/sjpg \
Drivers/lvgl-master/src/libs/tiny_ttf \
Drivers/lvgl-master/src/misc \
Drivers/lvgl-master/src/others/file_explorer \
Drivers/lvgl-master/src/others/fragment \
Drivers/lvgl-master/src/others/gridnav \
Drivers/lvgl-master/src/others/ime \
Drivers/lvgl-master/src/others/imgfont \
Drivers/lvgl-master/src/others/monkey \
Drivers/lvgl-master/src/others/msg \
Drivers/lvgl-master/src/others/snapshot \
Drivers/lvgl-master/src/others/sysmon \
Drivers/lvgl-master/src/themes/basic \
Drivers/lvgl-master/src/themes/default \
Drivers/lvgl-master/src/themes/mono \
Drivers/lvgl-master/src/widgets/animimg \
Drivers/lvgl-master/src/widgets/arc \
Drivers/lvgl-master/src/widgets/bar \
Drivers/lvgl-master/src/widgets/btn \
Drivers/lvgl-master/src/widgets/btnmatrix \
Drivers/lvgl-master/src/widgets/calendar \
Drivers/lvgl-master/src/widgets/canvas \
Drivers/lvgl-master/src/widgets/chart \
Drivers/lvgl-master/src/widgets/checkbox \
Drivers/lvgl-master/src/widgets/colorwheel \
Drivers/lvgl-master/src/widgets/dropdown \
Drivers/lvgl-master/src/widgets/img \
Drivers/lvgl-master/src/widgets/imgbtn \
Drivers/lvgl-master/src/widgets/keyboard \
Drivers/lvgl-master/src/widgets/label \
Drivers/lvgl-master/src/widgets/led \
Drivers/lvgl-master/src/widgets/line \
Drivers/lvgl-master/src/widgets/list \
Drivers/lvgl-master/src/widgets/menu \
Drivers/lvgl-master/src/widgets/meter \
Drivers/lvgl-master/src/widgets/msgbox \
Drivers/lvgl-master/src/widgets/objx_templ \
Drivers/lvgl-master/src/widgets/roller \
Drivers/lvgl-master/src/widgets/slider \
Drivers/lvgl-master/src/widgets/span \
Drivers/lvgl-master/src/widgets/spinbox \
Drivers/lvgl-master/src/widgets/spinner \
Drivers/lvgl-master/src/widgets/switch \
Drivers/lvgl-master/src/widgets/table \
Drivers/lvgl-master/src/widgets/tabview \
Drivers/lvgl-master/src/widgets/textarea \
Drivers/lvgl-master/src/widgets/tileview \
Drivers/lvgl-master/src/widgets/win \
Drivers/lvgl-master/tests/makefile \
Drivers/lvgl-master/tests/src \
Drivers/lvgl-master/tests/src/test_assets \
Drivers/lvgl-master/tests/src/test_cases \
Drivers/lvgl-master/tests/unity \

