################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/GC9A01A_Driver/Src \
Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/lvgl-8.3.7/demos/benchmark/assets \
Drivers/lvgl-8.3.7/demos/benchmark \
Drivers/lvgl-8.3.7/demos/keypad_encoder \
Drivers/lvgl-8.3.7/demos/music/assets \
Drivers/lvgl-8.3.7/demos/music \
Drivers/lvgl-8.3.7/demos/stress \
Drivers/lvgl-8.3.7/demos/widgets/assets \
Drivers/lvgl-8.3.7/demos/widgets \
Drivers/lvgl-8.3.7/env_support/rt-thread \
Drivers/lvgl-8.3.7/env_support/rt-thread/squareline \
Drivers/lvgl-8.3.7/examples/anim \
Drivers/lvgl-8.3.7/examples/assets \
Drivers/lvgl-8.3.7/examples/assets/emoji \
Drivers/lvgl-8.3.7/examples/event \
Drivers/lvgl-8.3.7/examples/get_started \
Drivers/lvgl-8.3.7/examples/layouts/flex \
Drivers/lvgl-8.3.7/examples/layouts/grid \
Drivers/lvgl-8.3.7/examples/libs/bmp \
Drivers/lvgl-8.3.7/examples/libs/ffmpeg \
Drivers/lvgl-8.3.7/examples/libs/freetype \
Drivers/lvgl-8.3.7/examples/libs/gif \
Drivers/lvgl-8.3.7/examples/libs/png \
Drivers/lvgl-8.3.7/examples/libs/qrcode \
Drivers/lvgl-8.3.7/examples/libs/rlottie \
Drivers/lvgl-8.3.7/examples/libs/sjpg \
Drivers/lvgl-8.3.7/examples/others/fragment \
Drivers/lvgl-8.3.7/examples/others/gridnav \
Drivers/lvgl-8.3.7/examples/others/ime \
Drivers/lvgl-8.3.7/examples/others/imgfont \
Drivers/lvgl-8.3.7/examples/others/monkey \
Drivers/lvgl-8.3.7/examples/others/msg \
Drivers/lvgl-8.3.7/examples/others/snapshot \
Drivers/lvgl-8.3.7/examples/porting \
Drivers/lvgl-8.3.7/examples/scroll \
Drivers/lvgl-8.3.7/examples/styles \
Drivers/lvgl-8.3.7/examples/widgets/animimg \
Drivers/lvgl-8.3.7/examples/widgets/arc \
Drivers/lvgl-8.3.7/examples/widgets/bar \
Drivers/lvgl-8.3.7/examples/widgets/btn \
Drivers/lvgl-8.3.7/examples/widgets/btnmatrix \
Drivers/lvgl-8.3.7/examples/widgets/calendar \
Drivers/lvgl-8.3.7/examples/widgets/canvas \
Drivers/lvgl-8.3.7/examples/widgets/chart \
Drivers/lvgl-8.3.7/examples/widgets/checkbox \
Drivers/lvgl-8.3.7/examples/widgets/colorwheel \
Drivers/lvgl-8.3.7/examples/widgets/dropdown \
Drivers/lvgl-8.3.7/examples/widgets/img \
Drivers/lvgl-8.3.7/examples/widgets/imgbtn \
Drivers/lvgl-8.3.7/examples/widgets/keyboard \
Drivers/lvgl-8.3.7/examples/widgets/label \
Drivers/lvgl-8.3.7/examples/widgets/led \
Drivers/lvgl-8.3.7/examples/widgets/line \
Drivers/lvgl-8.3.7/examples/widgets/list \
Drivers/lvgl-8.3.7/examples/widgets/menu \
Drivers/lvgl-8.3.7/examples/widgets/meter \
Drivers/lvgl-8.3.7/examples/widgets/msgbox \
Drivers/lvgl-8.3.7/examples/widgets/obj \
Drivers/lvgl-8.3.7/examples/widgets/roller \
Drivers/lvgl-8.3.7/examples/widgets/slider \
Drivers/lvgl-8.3.7/examples/widgets/span \
Drivers/lvgl-8.3.7/examples/widgets/spinbox \
Drivers/lvgl-8.3.7/examples/widgets/spinner \
Drivers/lvgl-8.3.7/examples/widgets/switch \
Drivers/lvgl-8.3.7/examples/widgets/table \
Drivers/lvgl-8.3.7/examples/widgets/tabview \
Drivers/lvgl-8.3.7/examples/widgets/textarea \
Drivers/lvgl-8.3.7/examples/widgets/tileview \
Drivers/lvgl-8.3.7/examples/widgets/win \
Drivers/lvgl-8.3.7/src/core \
Drivers/lvgl-8.3.7/src/draw/arm2d \
Drivers/lvgl-8.3.7/src/draw \
Drivers/lvgl-8.3.7/src/draw/nxp/pxp \
Drivers/lvgl-8.3.7/src/draw/nxp/vglite \
Drivers/lvgl-8.3.7/src/draw/sdl \
Drivers/lvgl-8.3.7/src/draw/stm32_dma2d \
Drivers/lvgl-8.3.7/src/draw/sw \
Drivers/lvgl-8.3.7/src/draw/swm341_dma2d \
Drivers/lvgl-8.3.7/src/extra/layouts/flex \
Drivers/lvgl-8.3.7/src/extra/layouts/grid \
Drivers/lvgl-8.3.7/src/extra/libs/bmp \
Drivers/lvgl-8.3.7/src/extra/libs/ffmpeg \
Drivers/lvgl-8.3.7/src/extra/libs/freetype \
Drivers/lvgl-8.3.7/src/extra/libs/fsdrv \
Drivers/lvgl-8.3.7/src/extra/libs/gif \
Drivers/lvgl-8.3.7/src/extra/libs/png \
Drivers/lvgl-8.3.7/src/extra/libs/qrcode \
Drivers/lvgl-8.3.7/src/extra/libs/rlottie \
Drivers/lvgl-8.3.7/src/extra/libs/sjpg \
Drivers/lvgl-8.3.7/src/extra \
Drivers/lvgl-8.3.7/src/extra/others/fragment \
Drivers/lvgl-8.3.7/src/extra/others/gridnav \
Drivers/lvgl-8.3.7/src/extra/others/ime \
Drivers/lvgl-8.3.7/src/extra/others/imgfont \
Drivers/lvgl-8.3.7/src/extra/others/monkey \
Drivers/lvgl-8.3.7/src/extra/others/msg \
Drivers/lvgl-8.3.7/src/extra/others/snapshot \
Drivers/lvgl-8.3.7/src/extra/themes/basic \
Drivers/lvgl-8.3.7/src/extra/themes/default \
Drivers/lvgl-8.3.7/src/extra/themes/mono \
Drivers/lvgl-8.3.7/src/extra/widgets/animimg \
Drivers/lvgl-8.3.7/src/extra/widgets/calendar \
Drivers/lvgl-8.3.7/src/extra/widgets/chart \
Drivers/lvgl-8.3.7/src/extra/widgets/colorwheel \
Drivers/lvgl-8.3.7/src/extra/widgets/imgbtn \
Drivers/lvgl-8.3.7/src/extra/widgets/keyboard \
Drivers/lvgl-8.3.7/src/extra/widgets/led \
Drivers/lvgl-8.3.7/src/extra/widgets/list \
Drivers/lvgl-8.3.7/src/extra/widgets/menu \
Drivers/lvgl-8.3.7/src/extra/widgets/meter \
Drivers/lvgl-8.3.7/src/extra/widgets/msgbox \
Drivers/lvgl-8.3.7/src/extra/widgets/span \
Drivers/lvgl-8.3.7/src/extra/widgets/spinbox \
Drivers/lvgl-8.3.7/src/extra/widgets/spinner \
Drivers/lvgl-8.3.7/src/extra/widgets/tabview \
Drivers/lvgl-8.3.7/src/extra/widgets/tileview \
Drivers/lvgl-8.3.7/src/extra/widgets/win \
Drivers/lvgl-8.3.7/src/font \
Drivers/lvgl-8.3.7/src/hal \
Drivers/lvgl-8.3.7/src/misc \
Drivers/lvgl-8.3.7/src/widgets \
Drivers/lvgl-8.3.7/tests/makefile \
Drivers/lvgl-8.3.7/tests/src \
Drivers/lvgl-8.3.7/tests/src/test_cases \
Drivers/lvgl-8.3.7/tests/src/test_fonts \
Drivers/lvgl-8.3.7/tests/unity \

